apiVersion: v1
kind: Pod 
metadata:
  name: taint-demo
spec:
  containers:
   - name: nginx
     image: nginx
     imagePullPolicy: Always
  nodeSelector:
     disktype: ssd 
  tolerations:
     - key1: "key1"
       operator: "Equal"
       value1: "value1"
       effect: "NoSchedule"
     - key2: "key1"
       operator: "Equal"
       value1: "value1"
       effect: "NoExecute"


