apiVersion: v1
kind: Pod 
metadata:
  name: taint-demo
spec:
  containers:
   - name: nginx
     image: nginx
     imagePullPolicy: Always
  nodeSelector:
     disktype: ssd 
  tolerations:
     - key: "key1"
       operator: "Equal"
       value: "value1"
       effect: "NoSchedule"
     - key: "key1"
       operator: "Equal"
       value: "value1"
       effect: "NoExecute"


