apiVersion: v1 
kind: Pod 
metadata: 
  name: node-affinity-demo
spec:
  affinity:
    nodeAffinity:
      requiredDuringSchedulingIgnoredDuringExecution:
        nodeSelectorTerms:
        - matchExpressions:
            - key: hardware
              operator: In 
              values: 
                - gpu
  containers:
    - name: affinity-demo 
      image: nginx


           