apiVersion: v1
kind: Pod 
metadata: 
 name: node-anti-affinity-demo
 labels:
   purpose: demo 
spec:
  nodeAffinity:
     requiredDuringSchedulingIgnoredDuringExecution:
      nodeSelectorTerms:
        - matchExpressions:
            - key: hardware
              operator: NotIn 
              values:
               - gpu
  containers:
    - name: with-node-anti-affinity
      image: nginx