apiVersion: v1
kind: Pod 
metadata: 
  name: pod-affinity-demo
  labels:
    name: app
    purpose: demo
spec:
  containers:
    - name: pod-1
      image: nginx
--- 
apiVersion: v1
kind: Pod
metadata: 
  name: pod-2
spec:
 podAffinity:
  #  requiredDuringSchedulingIgnoredDuringExecution:
  #     - labelSelector:
  #        matchExperssion:
  #          - key: name
  #            operator: In
  #            values: 
  #            - app
  #       topologyKey: "kubernetes.io/hostname"
  preferredDuringSchedulingIgnoredDuringExecution:
  - weight: 1
    podAffinityTerm:
      labelSelector:
        matchExperssions: 
          - key: name
            operator: In 
            values: 
              - app
      topologyKey: "kubernetes.io/hostname"
 containers:
  - name: pod-2
    image: nginx


             